DEF_FUNCTION (SIN, sin, 6)

DEF_FUNCTION (COS, cos, 7)

DEF_FUNCTION (TAN, tan, 8)

DEF_FUNCTION (CTG, ctg, 9)

DEF_FUNCTION (LN, ln, 10)

DEF_FUNCTION (EXP, exp, 11)

DEF_FUNCTION (SH, sh, 12)

DEF_FUNCTION (CH, ch, 13)

DEF_FUNCTION (TH, th, 14)

DEF_FUNCTION (CTH, cth, 15)
